name: Deploy HabitApp to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    name: Deploy Frontend → S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          cd frontend
          npm install

      - name: Build React
        run: |
          cd frontend
          npm run build

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Subir frontend a S3
        run: |
          aws s3 sync ./frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete